// This file is the source of truth for the dashboard's behaviour. The browser
// loads the compiled dashboard.js (generated by `npm run build`); never edit
// that artifact by hand.

const REFRESH_SECONDS = 5;

// A row whose container was actually updated (recreated on a new image/commit/
// base) within this window gets a green background that fades linearly to
// nothing as the update ages. Rows are rebuilt on every refresh, so the fade
// advances in REFRESH_SECONDS steps.
const UPDATED_HIGHLIGHT_MS = 10 * 60 * 1000;
const UPDATED_HIGHLIGHT_MAX_ALPHA = 0.22;
// rgb of --green (#3fb950) in dashboard.css.
const GREEN_RGB = "63,185,80";

// ApiContainer mirrors the JSON emitted by apiContainer in dashboard.go. Keeping
// it in sync is the whole point of the TypeScript rewrite: a renamed or
// wrong-typed field here is a compile error instead of a silent `undefined`.
interface ApiContainer {
  name: string;
  image: string;
  image_id: string;
  state: string;
  status: string;
  health: string;
  created: number;
  restarts?: number | null;
  auto_update: boolean;
  mode?: string;
  last_checked?: string | null;
  last_pulled?: string | null;
  last_updated?: string | null;
  update_available: boolean;
  current_ref?: string;
  available_ref?: string;
  error?: string;
  skipped?: boolean;
  skip_reason?: string;
}

// ApiResponse mirrors apiResponse in dashboard.go (the payload of /api/containers).
interface ApiResponse {
  generated_at: string;
  interval: string;
  dry_run: boolean;
  label: string;
  last_cycle?: string | null;
  next_cycle?: string | null;
  containers: ApiContainer[];
}

type Props = Record<string, string | null | undefined> | null;
type Child = string | Node | null | undefined;

// el builds a DOM node safely. Text content is set via textContent, never
// innerHTML, so container names and images from Docker can't inject markup.
function el(tag: string, props?: Props, ...children: Child[]): HTMLElement {
  const node = document.createElement(tag);
  if (props) {
    for (const [k, v] of Object.entries(props)) {
      if (v === null || v === undefined) continue;
      if (k === "class") node.className = v;
      else if (k === "title") node.title = v;
      else node.setAttribute(k, v);
    }
  }
  for (const c of children) {
    if (c === null || c === undefined) continue;
    node.appendChild(typeof c === "string" ? document.createTextNode(c) : c);
  }
  return node;
}

// fmtRelative renders an ISO timestamp as a compact "x ago" / "in x" string.
function fmtRelative(iso: string | null | undefined): string | null {
  if (!iso) return null;
  const then = new Date(iso).getTime();
  if (Number.isNaN(then)) return null;
  let secs = Math.round((Date.now() - then) / 1000);
  const future = secs < 0;
  secs = Math.abs(secs);
  const txt = humanDuration(secs);
  if (txt === "0s") return "just now";
  return future ? "in " + txt : txt + " ago";
}

function humanDuration(secs: number): string {
  const units: [string, number][] = [
    ["d", 86400],
    ["h", 3600],
    ["m", 60],
    ["s", 1],
  ];
  for (const [label, size] of units) {
    if (secs >= size) return Math.floor(secs / size) + label;
  }
  return "0s";
}

// uptimeText strips the health parenthetical from Docker's status string,
// leaving e.g. "Up 2 hours".
function uptimeText(c: ApiContainer): string | null {
  if (c.state !== "running") return null;
  return (c.status || "").replace(/\s*\(health[^)]*\)\s*/i, "").replace(/\s*\((un)?healthy\)\s*/i, "").trim() || null;
}

function stateCell(c: ApiContainer): HTMLElement {
  let dot = "dot-gray";
  if (c.health === "healthy") dot = "dot-green";
  else if (c.health === "unhealthy") dot = "dot-red";
  else if (c.health === "starting") dot = "dot-amber";
  else if (c.state === "running") dot = "dot-green";
  else if (c.state === "exited" || c.state === "dead") dot = "dot-red";

  const children: Child[] = [
    el("span", { class: "dot " + dot }),
    el("span", { class: "state-text" }, c.state || "unknown"),
  ];
  if (c.health) children.push(el("div", { class: "health-sub" }, c.health));
  return el("td", null, ...children);
}

// restartsCell renders Docker's restart count for the container. A nil count
// (container could not be inspected) shows "—"; zero is dimmed as the unremarkable
// healthy case; a positive count is highlighted to flag instability.
function restartsCell(c: ApiContainer): HTMLElement {
  const n = c.restarts;
  if (n === undefined || n === null) return el("td", { class: "up-na" }, "—");
  if (n === 0) return el("td", { class: "up-na" }, "0");
  const title = "Restarted " + n + " time" + (n !== 1 ? "s" : "") + " since the container was last (re)created";
  return el("td", { class: "restarts-warn", title }, String(n));
}

function autoUpdateCell(c: ApiContainer): HTMLElement {
  if (!c.auto_update) {
    return el("td", null, el("span", { class: "badge badge-manual", title: "Not monitored by docker-updater" }, "Manual"));
  }
  const cls = c.mode === "git" ? "badge badge-git" : "badge badge-auto";
  return el("td", null, el("span", { class: cls }, "Auto · " + (c.mode || "image")));
}

// heldBackReason explains why a detected update has not been applied. The three
// cases mirror the backend's mutually-exclusive branches (see state.go Record):
// an error while applying, a pre-check that skipped it, or dry-run mode — which
// is the only remaining way an update can be available without error or skip.
function heldBackReason(c: ApiContainer): string {
  if (c.error) return "error: " + c.error;
  if (c.skipped) return "skipped: " + (c.skip_reason || "pre-check");
  return "dry-run — not applied";
}

function upstreamCell(c: ApiContainer): HTMLElement {
  const td = el("td", null);
  if (!c.auto_update) {
    td.appendChild(el("span", { class: "up-na" }, "—"));
    return td;
  }
  // An available update means one was detected but held back. Always surface it
  // as such — even when it also errored — so the row matches the "updates
  // pending" count instead of hiding behind a bare "error".
  if (c.update_available) {
    td.appendChild(el("span", { class: "up-available" }, "update available"));
    let detail = "";
    if (c.current_ref || c.available_ref) {
      detail = (c.current_ref || "?") + " → " + (c.available_ref || "?");
    }
    const reason = heldBackReason(c);
    detail = detail ? detail + " · " + reason : reason;
    td.appendChild(el("div", { class: "detail" }, detail));
    return td;
  }
  // Errored with no newer ref detected: a plain failure, not a pending update.
  if (c.error) {
    td.appendChild(el("span", { class: "up-error" }, "error"));
    td.appendChild(el("div", { class: "detail" }, c.error));
    return td;
  }
  // Up to date.
  td.appendChild(el("span", { class: "up-uptodate" }, "up to date"));
  const updated = fmtRelative(c.last_updated);
  if (updated) td.appendChild(el("div", { class: "detail" }, "updated " + updated));
  return td;
}

// pending reports whether a container has an update detected but not yet applied
// — the exact condition counted by the "updates pending" card.
function pending(c: ApiContainer): boolean {
  return Boolean(c.auto_update && c.update_available);
}

// isOnline splits containers into the online/offline group halves. Offline is
// the not-up states: exited, dead, or created (never started); everything else
// (running, restarting, paused, removing) counts as online.
function isOnline(c: ApiContainer): boolean {
  return c.state !== "exited" && c.state !== "dead" && c.state !== "created";
}

// The four dashboard sections, in display order. Every container lands in
// exactly one: managed (has the auto-update label) × online/offline. The ids
// match the <details> elements in index.html ("-summary" / "-rows" suffixes).
interface Group {
  id: string;
  label: string;
  match: (c: ApiContainer) => boolean;
}

const GROUPS: Group[] = [
  { id: "group-managed-online", label: "Managed · online", match: (c) => c.auto_update && isOnline(c) },
  { id: "group-managed-offline", label: "Managed · offline", match: (c) => c.auto_update && !isOnline(c) },
  { id: "group-unmanaged-online", label: "Unmanaged · online", match: (c) => !c.auto_update && isOnline(c) },
  { id: "group-unmanaged-offline", label: "Unmanaged · offline", match: (c) => !c.auto_update && !isOnline(c) },
];

// searchQuery returns the normalized filter-box text: trimmed and lowercased,
// "" meaning "no filter".
function searchQuery(): string {
  const box = document.getElementById("search") as HTMLInputElement | null;
  return box ? box.value.trim().toLowerCase() : "";
}

// matchesQuery is a case-insensitive substring match against the container
// name and image; either matching keeps the row visible.
function matchesQuery(c: ApiContainer, query: string): boolean {
  if (!query) return true;
  return (c.name || "").toLowerCase().includes(query) || (c.image || "").toLowerCase().includes(query);
}

// updatedHighlight computes the fading green background for a container whose
// last update was applied within UPDATED_HIGHLIGHT_MS: full strength when
// fresh, linearly down to zero at the end of the window. Returns null once the
// window has passed (or when the container was never updated).
function updatedHighlight(c: ApiContainer, now: number): { background: string; title: string } | null {
  if (!c.last_updated) return null;
  const then = new Date(c.last_updated).getTime();
  if (Number.isNaN(then)) return null;
  const age = Math.max(0, now - then); // clamp so slight clock skew reads as fresh
  if (age >= UPDATED_HIGHLIGHT_MS) return null;
  const alpha = UPDATED_HIGHLIGHT_MAX_ALPHA * (1 - age / UPDATED_HIGHLIGHT_MS);
  return {
    background: "rgba(" + GREEN_RGB + "," + alpha.toFixed(3) + ")",
    title: "updated " + (fmtRelative(c.last_updated) || "just now"),
  };
}

function row(c: ApiContainer): HTMLElement {
  const nameCell = el("td", null,
    el("span", { class: "cname" }, c.name || "—"),
    el("div", { class: "cmeta" },
      c.image || "—",
      c.image_id ? " · " : null,
      c.image_id ? el("span", { class: "cref" }, c.image_id) : null,
    ),
  );

  const uptime = uptimeText(c);
  const lastChecked = c.auto_update ? (fmtRelative(c.last_checked) || "—") : "—";
  const lastPulled = c.auto_update ? (fmtRelative(c.last_pulled) || "—") : "—";

  const highlight = updatedHighlight(c, Date.now());
  const tr = el("tr", { class: pending(c) ? "row-pending" : null, title: highlight ? highlight.title : null },
    nameCell,
    autoUpdateCell(c),
    stateCell(c),
    el("td", { class: uptime ? null : "up-na" }, uptime || "—"),
    restartsCell(c),
    el("td", { class: lastChecked === "—" ? "up-na" : null }, lastChecked),
    el("td", { class: lastPulled === "—" ? "up-na" : null }, lastPulled),
    upstreamCell(c),
  );
  // Inline style so the alpha can fade with age. It wins over .row-pending's
  // class background, which is acceptable: a just-updated container should not
  // also be pending, and the pending left-edge accent still shows regardless.
  if (highlight) tr.style.background = highlight.background;
  return tr;
}

function setText(id: string, text: string | number): void {
  const node = document.getElementById(id);
  if (node) node.textContent = String(text);
}

function render(data: ApiResponse): void {
  const containers = data.containers || [];

  // The summary cards are fleet totals: computed over every container, never
  // narrowed by the search filter.
  const auto = containers.filter((c) => c.auto_update).length;
  const updates = containers.filter(pending).length;
  const errors = containers.filter((c) => c.auto_update && c.error).length;

  setText("stat-total", containers.length);
  setText("stat-auto", auto);
  setText("stat-manual", containers.length - auto);
  setText("stat-updates", updates);
  setText("stat-errors", errors);

  // The card jumps to the held-back rows; only make it actionable when there are any.
  const updatesCard = document.getElementById("card-updates");
  if (updatesCard) updatesCard.classList.toggle("clickable", updates > 0);

  document.getElementById("dry-run-badge")!.classList.toggle("hidden", !data.dry_run);
  setText("cfg-interval", data.interval || "—");
  setText("cfg-label", data.label || "—");
  setText("refresh-interval", REFRESH_SECONDS);

  const lastCycle = fmtRelative(data.last_cycle);
  setText("last-cycle", lastCycle ? "Last check " + lastCycle : "No check yet");
  const nextCycle = fmtRelative(data.next_cycle);
  setText("next-cycle", nextCycle ? "Next check " + nextCycle : "");
  setText("refreshed", "Updated " + new Date(data.generated_at).toLocaleTimeString());

  const query = searchQuery();
  const visible = containers.filter((c) => matchesQuery(c, query));

  // Only tbody contents, summary counts, and the hidden class change per
  // render. The <details> elements themselves are static (and their open state
  // is never touched), so the user's expand/collapse choices survive refreshes.
  for (const g of GROUPS) {
    const members = visible.filter(g.match);
    document.getElementById(g.id + "-rows")!.replaceChildren(...members.map(row));
    document.getElementById(g.id + "-summary")!.textContent = g.label + " (" + members.length + ")";
    document.getElementById(g.id)!.classList.toggle("hidden", members.length === 0);
  }

  // Every container lands in exactly one group, so "all groups hidden" is
  // exactly "no visible containers": none exist, or the filter matched none.
  const empty = document.getElementById("empty")!;
  empty.textContent = query && containers.length > 0
    ? 'No containers match "' + query + '".'
    : "No containers found.";
  empty.classList.toggle("hidden", visible.length > 0);
}

// latestData holds the most recent successful /api/containers payload so the
// search box can re-render instantly without refetching; the poll replaces it.
let latestData: ApiResponse | null = null;

async function refresh(): Promise<void> {
  const banner = document.getElementById("error-banner")!;
  try {
    const resp = await fetch("api/containers", { cache: "no-store" });
    if (!resp.ok) throw new Error("HTTP " + resp.status + ": " + (await resp.text()));
    latestData = (await resp.json()) as ApiResponse;
    render(latestData);
    banner.classList.add("hidden");
  } catch (err) {
    banner.textContent = "Failed to load container data: " + (err instanceof Error ? err.message : String(err));
    banner.classList.remove("hidden");
  }
}

// jumpToPending scrolls to the first container with a held-back update, flashing
// it so "N updates pending" always points at concrete rows. Every row lives in
// a collapsible group, so reveal the group holding the target first.
function jumpToPending(): void {
  const first = document.querySelector<HTMLElement>(".row-pending");
  if (!first) return;
  const section = first.closest("details");
  if (section) section.open = true;
  first.scrollIntoView({ behavior: "smooth", block: "center" });
  first.classList.remove("row-flash");
  void first.offsetWidth; // reflow so the animation restarts on repeat clicks
  first.classList.add("row-flash");
}

// onSearchInput re-renders the groups from the last fetched payload — no
// refetch; the poll keeps replacing latestData underneath as usual.
function onSearchInput(): void {
  if (latestData) render(latestData);
}

const updatesCard = document.getElementById("card-updates");
if (updatesCard) updatesCard.addEventListener("click", jumpToPending);

const searchBox = document.getElementById("search") as HTMLInputElement | null;
if (searchBox) searchBox.addEventListener("input", onSearchInput);

// Keyboard niceties: "/" focuses the filter box, Escape clears it.
document.addEventListener("keydown", (e: KeyboardEvent) => {
  if (!searchBox) return;
  const target = e.target instanceof HTMLElement ? e.target : null;
  const typing = target !== null &&
    (target.tagName === "INPUT" || target.tagName === "TEXTAREA" || target.isContentEditable);
  if (e.key === "/" && !typing) {
    e.preventDefault();
    searchBox.focus();
    searchBox.select();
  } else if (e.key === "Escape" && target === searchBox) {
    searchBox.value = "";
    onSearchInput();
    searchBox.blur();
  }
});

void refresh();
setInterval(refresh, REFRESH_SECONDS * 1000);
