// This file is the source of truth for the dashboard's behaviour. The browser
// loads the compiled dashboard.js (generated by `npm run build`); never edit
// that artifact by hand.

const REFRESH_SECONDS = 5;

// A row whose container was actually updated (recreated on a new image/commit/
// base) within this window gets a green background that fades linearly to
// nothing as the update ages. Rows are rebuilt on every refresh, so the fade
// advances in REFRESH_SECONDS steps.
const UPDATED_HIGHLIGHT_MS = 10 * 60 * 1000;
const UPDATED_HIGHLIGHT_MAX_ALPHA = 0.22;
// rgb of --green (#3fb950) in dashboard.css.
const GREEN_RGB = "63,185,80";

// ApiContainer mirrors the JSON emitted by apiContainer in dashboard.go. Keeping
// it in sync is the whole point of the TypeScript rewrite: a renamed or
// wrong-typed field here is a compile error instead of a silent `undefined`.
interface ApiContainer {
  name: string;
  image: string;
  image_id: string;
  state: string;
  status: string;
  health: string;
  created: number;
  restarts?: number | null;
  auto_update: boolean;
  mode?: string;
  // Still served by /api/containers, but not rendered: every monitored
  // container is checked in the same cycle, so a per-row copy of the header's
  // "Last check <ago>" told the operator nothing.
  last_checked?: string | null;
  last_pulled?: string | null;
  last_updated?: string | null;
  update_available: boolean;
  current_ref?: string;
  available_ref?: string;
  error?: string;
  skipped?: boolean;
  skip_reason?: string;
  // Configuration notes, not failures: no standard
  // /.well-known/docker-updater/ endpoints, or nonstandard label overrides.
  warnings?: string[];
}

// ApiResponse mirrors apiResponse in dashboard.go (the payload of /api/containers).
interface ApiResponse {
  generated_at: string;
  interval: string;
  dry_run: boolean;
  label: string;
  version?: string;
  last_cycle?: string | null;
  next_cycle?: string | null;
  containers: ApiContainer[];
}

type Props = Record<string, string | null | undefined> | null;
type Child = string | Node | null | undefined;

// el builds a DOM node safely. Text content is set via textContent, never
// innerHTML, so container names and images from Docker can't inject markup.
function el(tag: string, props?: Props, ...children: Child[]): HTMLElement {
  const node = document.createElement(tag);
  if (props) {
    for (const [k, v] of Object.entries(props)) {
      if (v === null || v === undefined) continue;
      if (k === "class") node.className = v;
      else if (k === "title") node.title = v;
      else node.setAttribute(k, v);
    }
  }
  for (const c of children) {
    if (c === null || c === undefined) continue;
    node.appendChild(typeof c === "string" ? document.createTextNode(c) : c);
  }
  return node;
}

// fmtRelative renders an ISO timestamp as a compact "x ago" / "in x" string.
function fmtRelative(iso: string | null | undefined): string | null {
  if (!iso) return null;
  const then = new Date(iso).getTime();
  if (Number.isNaN(then)) return null;
  let secs = Math.round((Date.now() - then) / 1000);
  const future = secs < 0;
  secs = Math.abs(secs);
  const txt = humanDuration(secs);
  if (txt === "0s") return "just now";
  return future ? "in " + txt : txt + " ago";
}

function humanDuration(secs: number): string {
  const units: [string, number][] = [
    ["d", 86400],
    ["h", 3600],
    ["m", 60],
    ["s", 1],
  ];
  for (const [label, size] of units) {
    if (secs >= size) return Math.floor(secs / size) + label;
  }
  return "0s";
}

// uptimeText strips the health parenthetical from Docker's status string,
// leaving e.g. "Up 2 hours".
function uptimeText(c: ApiContainer): string | null {
  if (c.state !== "running") return null;
  return (c.status || "").replace(/\s*\(health[^)]*\)\s*/i, "").replace(/\s*\((un)?healthy\)\s*/i, "").trim() || null;
}

// The text of each table cell lives in its own function, and both the cell
// builder and stateSnapshot() call it. Anything the table draws is therefore
// reachable by the copy button by construction — a value the snapshot could
// omit is a value no column can render either.

// stateIndicator is the colour of the row's state dot: the reported health
// when Docker has one, else the container's own state.
function stateIndicator(c: ApiContainer): string {
  if (c.health === "healthy") return "green";
  if (c.health === "unhealthy") return "red";
  if (c.health === "starting") return "amber";
  if (c.state === "running") return "green";
  if (c.state === "exited" || c.state === "dead") return "red";
  return "gray";
}

function stateText(c: ApiContainer): string {
  return c.state || "unknown";
}

function stateCell(c: ApiContainer): HTMLElement {
  const children: Child[] = [
    el("span", { class: "dot dot-" + stateIndicator(c) }),
    el("span", { class: "state-text" }, stateText(c)),
  ];
  if (c.health) children.push(el("div", { class: "health-sub" }, c.health));
  return el("td", null, ...children);
}

// restartsText is the Restarts column: Docker's restart count, or "—" when the
// container could not be inspected.
function restartsText(c: ApiContainer): string {
  const n = c.restarts;
  return n === undefined || n === null ? "—" : String(n);
}

// restartsCell dims the unremarkable cases (uninspectable, zero) and highlights
// a positive count to flag instability.
function restartsCell(c: ApiContainer): HTMLElement {
  const n = c.restarts;
  const text = restartsText(c);
  if (n === undefined || n === null || n === 0) return el("td", { class: "up-na" }, text);
  const title = "Restarted " + n + " time" + (n !== 1 ? "s" : "") + " since the container was last (re)created";
  return el("td", { class: "restarts-warn", title }, text);
}

// monitoringText is the Auto-update column's badge text.
function monitoringText(c: ApiContainer): string {
  return c.auto_update ? "Auto · " + (c.mode || "image") : "Manual";
}

function autoUpdateCell(c: ApiContainer): HTMLElement {
  if (!c.auto_update) {
    return el("td", null, el("span", { class: "badge badge-manual", title: "Not monitored by docker-updater" }, monitoringText(c)));
  }
  const cls = c.mode === "git" ? "badge badge-git" : "badge badge-auto";
  return el("td", null, el("span", { class: cls }, monitoringText(c)));
}

// lastPulledText is the Last pulled column: how long ago a newer image was
// actually downloaded. Unmonitored containers are never pulled.
function lastPulledText(c: ApiContainer): string {
  return c.auto_update ? (fmtRelative(c.last_pulled) || "—") : "—";
}

// heldBackReason explains why a detected update has not been applied. The three
// cases mirror the backend's mutually-exclusive branches (see state.go Record):
// an error while applying, a pre-check that skipped it, or dry-run mode — which
// is the only remaining way an update can be available without error or skip.
function heldBackReason(c: ApiContainer): string {
  if (c.error) return "error: " + c.error;
  if (c.skipped) return "skipped: " + (c.skip_reason || "pre-check");
  return "dry-run — not applied";
}

// UpstreamView is the Upstream column: a one-word verdict and the detail line
// under it (a ref transition, the reason an update is held back, or the full
// error text).
interface UpstreamView {
  cls: string;
  status: string;
  detail: string | null;
}

function upstreamView(c: ApiContainer): UpstreamView {
  if (!c.auto_update) return { cls: "up-na", status: "—", detail: null };
  // An available update means one was detected but held back. Always surface it
  // as such — even when it also errored — so the row matches the "updates
  // pending" count instead of hiding behind a bare "error".
  if (c.update_available) {
    let detail = "";
    if (c.current_ref || c.available_ref) {
      detail = (c.current_ref || "?") + " → " + (c.available_ref || "?");
    }
    const reason = heldBackReason(c);
    return { cls: "up-available", status: "update available", detail: detail ? detail + " · " + reason : reason };
  }
  // Errored with no newer ref detected: a plain failure, not a pending update.
  if (c.error) return { cls: "up-error", status: "error", detail: c.error };
  // Up to date.
  const updated = fmtRelative(c.last_updated);
  return { cls: "up-uptodate", status: "up to date", detail: updated ? "updated " + updated : null };
}

function upstreamCell(c: ApiContainer): HTMLElement {
  const view = upstreamView(c);
  const td = el("td", null, el("span", { class: view.cls }, view.status));
  if (view.detail) td.appendChild(el("div", { class: "detail" }, view.detail));
  return td;
}

// errored is the exact predicate behind the "errors" card: a monitored
// container whose last check or update attempt failed.
function errored(c: ApiContainer): boolean {
  return Boolean(c.auto_update && c.error);
}

// errorReport renders every current error as plain text for pasting into an
// issue or a chat. One block per container: what it is, what it was trying to
// move to, and the full untruncated error the Upstream column can only show a
// clipped version of.
function errorReport(data: ApiResponse): string {
  const rows = (data.containers || []).filter(errored);
  const header = "docker-updater — " + rows.length + " error" + (rows.length === 1 ? "" : "s") +
    " at " + (data.generated_at || new Date().toISOString()) +
    (data.version ? " (build " + data.version + ")" : "");
  const blocks = rows.map((c) => {
    const lines = [(c.name || "?") + "  [" + (c.image || "?") + "]"];
    lines.push("  state: " + (c.state || "unknown") + (c.health ? " (" + c.health + ")" : ""));
    if (c.update_available) {
      const refs = c.current_ref || c.available_ref
        ? ": " + (c.current_ref || "?") + " -> " + (c.available_ref || "?")
        : "";
      lines.push("  update available" + refs);
    }
    if (c.skipped) lines.push("  skipped: " + (c.skip_reason || "pre-check"));
    lines.push("  error: " + (c.error || ""));
    return lines.join("\n");
  });
  return [header, ...blocks].join("\n\n") + "\n";
}

// ---------------------------------------------------------------------------
// The state the page is drawn from
//
// One object: the served /api/containers payload, plus the state the server
// cannot know — what the operator typed into the filter, which sections they
// expanded, and whether the last poll failed. render() draws exactly this
// object and the copy button serializes exactly this object, so a paste
// reproduces the page rather than describing it.
//
// Deliberately NOT in here: the summary counts, the group headings, uptime
// strings, the Upstream verdict. Every one is arithmetic over the payload, and
// keeping a second copy of a fact beside the fact is how the two drift apart.
// render() computes them on the way to the DOM, every time.
// ---------------------------------------------------------------------------

interface UiState {
  page_url: string;
  refresh_seconds: number;
  // The filter box verbatim, so a re-render restores what was typed rather
  // than the normalized form matching uses.
  query: string;
  expanded: Record<string, boolean>;
  // Set only when the last poll failed — and then the containers below it are
  // the last payload that arrived, not the current one. This is the one thing
  // on the page that no payload can carry, because it exists exactly when none
  // did.
  error_banner: string | null;
}

type DashboardState = ApiResponse & { ui: UiState };

// stateSnapshot serializes the state the page was drawn from, stamped with the
// moment of the copy.
function stateSnapshot(state: DashboardState): string {
  return JSON.stringify({ captured_at: new Date().toISOString(), ...state }, null, 2) + "\n";
}

// copyText writes to the clipboard, falling back to a hidden textarea +
// execCommand: the dashboard is normally served over plain http on a LAN, where
// navigator.clipboard does not exist (non-secure context).
async function copyText(text: string): Promise<boolean> {
  try {
    if (window.isSecureContext && navigator.clipboard) {
      await navigator.clipboard.writeText(text);
      return true;
    }
  } catch {
    // Permission denied or an unavailable API — try the legacy path below.
  }
  const ta = el("textarea", { style: "position:fixed;top:-1000px;opacity:0;" }) as HTMLTextAreaElement;
  ta.value = text;
  document.body.appendChild(ta);
  ta.select();
  let ok = false;
  try {
    ok = document.execCommand("copy");
  } catch {
    ok = false;
  }
  ta.remove();
  return ok;
}

// How long a copy button shows "copied" / "copy failed" before its real label
// comes back.
const COPY_FEEDBACK_MS = 1500;

// copyResetTimers holds the pending label-restore timer per button id. Keyed by
// id so one button's feedback never cancels the other's, and so a render that
// lands mid-feedback leaves that button's label alone.
const copyResetTimers = new Map<string, number>();

// flashCopyResult copies text and shows the outcome on the button itself, then
// hands the label back to updateCopyButtons once the flash expires.
async function flashCopyResult(btn: HTMLButtonElement, text: string): Promise<void> {
  const ok = await copyText(text);
  btn.textContent = ok ? "copied" : "copy failed";
  const pending = copyResetTimers.get(btn.id);
  if (pending !== undefined) clearTimeout(pending);
  copyResetTimers.set(btn.id, setTimeout(() => {
    copyResetTimers.delete(btn.id);
    updateCopyButtons(currentState);
  }, COPY_FEEDBACK_MS));
}

function errorCount(data: ApiResponse | null): number {
  return data ? (data.containers || []).filter(errored).length : 0;
}

// updateCopyButtons keeps both copy buttons' labels and enabled state in step
// with the latest payload. Called from render(), so it tracks every poll.
// Neither button is enabled while it has nothing to copy: the errors button
// until something errors, the state button until the first payload arrives.
function updateCopyButtons(data: ApiResponse | null): void {
  const errors = errorCount(data);
  const errorsBtn = document.getElementById("copy-errors") as HTMLButtonElement | null;
  if (errorsBtn && !copyResetTimers.has("copy-errors")) {
    errorsBtn.disabled = errors === 0;
    errorsBtn.textContent = errors > 0 ? "copy " + errors : "copy";
  }
  const stateBtn = document.getElementById("copy-state") as HTMLButtonElement | null;
  if (stateBtn && !copyResetTimers.has("copy-state")) {
    stateBtn.disabled = data === null;
    stateBtn.textContent = "copy JSON";
  }
}

async function onCopyErrors(): Promise<void> {
  const btn = document.getElementById("copy-errors") as HTMLButtonElement | null;
  if (!btn || !currentState) return;
  await flashCopyResult(btn, errorReport(currentState));
}

async function onCopyState(): Promise<void> {
  const btn = document.getElementById("copy-state") as HTMLButtonElement | null;
  if (!btn || !currentState) return;
  await flashCopyResult(btn, stateSnapshot(currentState));
}

// pending reports whether a container has an update detected but not yet applied
// — the exact condition counted by the "updates pending" card.
function pending(c: ApiContainer): boolean {
  return Boolean(c.auto_update && c.update_available);
}

// isOnline splits containers into the online/offline group halves. Offline is
// the not-up states: exited, dead, or created (never started); everything else
// (running, restarting, paused, removing) counts as online.
function isOnline(c: ApiContainer): boolean {
  return c.state !== "exited" && c.state !== "dead" && c.state !== "created";
}

// The four dashboard sections, in display order. Every container lands in
// exactly one: managed (has the auto-update label) × online/offline. The ids
// match the <details> elements in index.html ("-summary" / "-rows" suffixes).
interface Group {
  id: string;
  label: string;
  match: (c: ApiContainer) => boolean;
}

const GROUPS: Group[] = [
  { id: "group-managed-online", label: "Managed · online", match: (c) => c.auto_update && isOnline(c) },
  { id: "group-managed-offline", label: "Managed · offline", match: (c) => c.auto_update && !isOnline(c) },
  { id: "group-unmanaged-online", label: "Unmanaged · online", match: (c) => !c.auto_update && isOnline(c) },
  { id: "group-unmanaged-offline", label: "Unmanaged · offline", match: (c) => !c.auto_update && !isOnline(c) },
];

// searchBoxValue returns the filter box's text as typed. The state carries it
// verbatim (so re-rendering can restore it without rewriting what someone is
// mid-way through typing); normalizing for matching is normalizeQuery's job.
function searchBoxValue(): string {
  const box = document.getElementById("search") as HTMLInputElement | null;
  return box ? box.value : "";
}

function normalizeQuery(raw: string): string {
  return raw.trim().toLowerCase();
}

// matchesQuery is a case-insensitive substring match against the container
// name and image; either matching keeps the row visible. `query` is normalized.
function matchesQuery(c: ApiContainer, query: string): boolean {
  if (!query) return true;
  return (c.name || "").toLowerCase().includes(query) || (c.image || "").toLowerCase().includes(query);
}

// expandedGroups reads which sections are open. Collapsing one hides its rows,
// so it is part of what the page is showing and belongs in the state.
function expandedGroups(): Record<string, boolean> {
  const out: Record<string, boolean> = {};
  for (const g of GROUPS) {
    const section = document.getElementById(g.id) as HTMLDetailsElement | null;
    if (section) out[g.id] = section.open;
  }
  return out;
}

// updatedHighlight computes the fading green background for a container whose
// last update was applied within UPDATED_HIGHLIGHT_MS: full strength when
// fresh, linearly down to zero at the end of the window. Returns null once the
// window has passed (or when the container was never updated).
function updatedHighlight(c: ApiContainer, now: number): { background: string; title: string } | null {
  if (!c.last_updated) return null;
  const then = new Date(c.last_updated).getTime();
  if (Number.isNaN(then)) return null;
  const age = Math.max(0, now - then); // clamp so slight clock skew reads as fresh
  if (age >= UPDATED_HIGHLIGHT_MS) return null;
  const alpha = UPDATED_HIGHLIGHT_MAX_ALPHA * (1 - age / UPDATED_HIGHLIGHT_MS);
  return {
    background: "rgba(" + GREEN_RGB + "," + alpha.toFixed(3) + ")",
    title: "updated " + (fmtRelative(c.last_updated) || "just now"),
  };
}

// warningLines renders a container's configuration warnings under its name:
// amber, one line each, full text (they name the label or endpoint to fix).
function warningLines(c: ApiContainer): HTMLElement[] {
  return (c.warnings || []).map((w) => el("div", { class: "warn", title: w }, "⚠ " + w));
}

function row(c: ApiContainer): HTMLElement {
  const nameCell = el("td", null,
    el("span", { class: "cname" }, c.name || "—"),
    el("div", { class: "cmeta" },
      c.image || "—",
      c.image_id ? " · " : null,
      c.image_id ? el("span", { class: "cref" }, c.image_id) : null,
    ),
    ...warningLines(c),
  );

  const uptime = uptimeText(c);
  const lastPulled = lastPulledText(c);

  const highlight = updatedHighlight(c, Date.now());
  const tr = el("tr", { class: pending(c) ? "row-pending" : null, title: highlight ? highlight.title : null },
    nameCell,
    autoUpdateCell(c),
    stateCell(c),
    el("td", { class: uptime ? null : "up-na" }, uptime || "—"),
    restartsCell(c),
    el("td", { class: lastPulled === "—" ? "up-na" : null }, lastPulled),
    upstreamCell(c),
  );
  // Inline style so the alpha can fade with age. It wins over .row-pending's
  // class background, which is acceptable: a just-updated container should not
  // also be pending, and the pending left-edge accent still shows regardless.
  if (highlight) tr.style.background = highlight.background;
  return tr;
}

function setText(id: string, text: string | number): void {
  const node = document.getElementById(id);
  if (node) node.textContent = String(text);
}

// render draws the state. Everything it puts on screen is derived here, from
// that one object — nothing is read back out of the DOM, and nothing it draws
// is stored. Given the same state it produces the same page, which is what
// makes a copied snapshot reproducible.
function render(state: DashboardState): void {
  const data: ApiResponse = state;
  const ui = state.ui;
  const containers = data.containers || [];

  // The summary cards are fleet totals: computed over every container, never
  // narrowed by the search filter.
  const auto = containers.filter((c) => c.auto_update).length;
  const updates = containers.filter(pending).length;
  const errors = errorCount(data);

  setText("stat-total", containers.length);
  setText("stat-auto", auto);
  setText("stat-manual", containers.length - auto);
  setText("stat-updates", updates);
  setText("stat-errors", errors);

  // The card jumps to the held-back rows; only make it actionable when there are any.
  const updatesCard = document.getElementById("card-updates");
  if (updatesCard) updatesCard.classList.toggle("clickable", updates > 0);

  updateCopyButtons(state);

  document.getElementById("dry-run-badge")!.classList.toggle("hidden", !data.dry_run);
  setText("cfg-interval", data.interval || "—");
  setText("cfg-label", data.label || "—");
  setText("refresh-interval", ui.refresh_seconds);

  // The banner is the one thing on the page no payload can carry: it is up
  // exactly when the last poll produced no payload at all.
  const banner = document.getElementById("error-banner")!;
  banner.textContent = ui.error_banner || "";
  banner.classList.toggle("hidden", ui.error_banner === null);

  // The updater's own build hash: shortened for the footer, full SHA on
  // hover. Guarded lookup (like card-updates) rather than REQUIRED_IDS, since
  // the dashboard works fine without the footer element.
  const versionNode = document.getElementById("build-version");
  if (versionNode) {
    const v = data.version || "";
    versionNode.textContent = v ? v.slice(0, 12) : "—";
    versionNode.title = v ? "docker-updater build " + v : "";
  }

  const lastCycle = fmtRelative(data.last_cycle);
  setText("last-cycle", lastCycle ? "Last check " + lastCycle : "No check yet");
  const nextCycle = fmtRelative(data.next_cycle);
  setText("next-cycle", nextCycle ? "Next check " + nextCycle : "");
  setText("refreshed", "Updated " + new Date(data.generated_at).toLocaleTimeString());

  // Writing the box back is what lets a state rendered into a fresh page carry
  // its filter with it. Guarded, so re-rendering while someone types does not
  // move their cursor.
  const box = document.getElementById("search") as HTMLInputElement;
  if (box.value !== ui.query) box.value = ui.query;

  const query = normalizeQuery(ui.query);
  const visible = containers.filter((c) => matchesQuery(c, query));

  // Row contents, summary counts, the hidden class, and the open state change
  // per render. Applying `open` from the state is what makes a re-render
  // reproduce the page; in normal use it writes back the value it was read
  // from, so an expand/collapse survives every poll.
  for (const g of GROUPS) {
    const members = visible.filter(g.match);
    document.getElementById(g.id + "-rows")!.replaceChildren(...members.map(row));
    document.getElementById(g.id + "-summary")!.textContent = g.label + " (" + members.length + ")";
    const section = document.getElementById(g.id) as HTMLDetailsElement;
    section.classList.toggle("hidden", members.length === 0);
    const open = ui.expanded[g.id];
    if (open !== undefined && section.open !== open) section.open = open;
  }

  // Every container lands in exactly one group, so "all groups hidden" is
  // exactly "no visible containers": none exist, or the filter matched none.
  const empty = document.getElementById("empty")!;
  empty.textContent = query && containers.length > 0
    ? 'No containers match "' + ui.query.trim() + '".'
    : "No containers found.";
  empty.classList.toggle("hidden", visible.length > 0);
}

// The two inputs the state is assembled from: the last payload that arrived
// (kept so the filter can re-render without refetching), and the failure of the
// most recent poll, if it failed.
let latestData: ApiResponse | null = null;
let pollFailure: string | null = null;

// currentState is the object the page was last drawn from, and the one the copy
// button serializes. Null until the first payload arrives.
let currentState: DashboardState | null = null;

// repaint rebuilds the state from those inputs plus the browser-side state, and
// draws it. Every path that changes anything the page shows ends here, so the
// object and the screen are never out of step.
function repaint(): void {
  if (!latestData) {
    // Nothing has arrived yet: there is no state to draw, only the failure to
    // report. The copy button stays disabled, having nothing to copy.
    const banner = document.getElementById("error-banner")!;
    banner.textContent = pollFailure || "";
    banner.classList.toggle("hidden", pollFailure === null);
    return;
  }
  currentState = {
    ui: {
      page_url: location.href,
      refresh_seconds: REFRESH_SECONDS,
      query: searchBoxValue(),
      expanded: expandedGroups(),
      error_banner: pollFailure,
    },
    ...latestData,
  };
  render(currentState);
}

// OUT_OF_SYNC_HINT is the human-readable diagnosis for mixed dashboard assets:
// an index.html from one build paired with a dashboard.js/css from another
// (a cache or proxy in front of the server, or two docker-updater containers
// answering the same host).
const OUT_OF_SYNC_HINT =
  "Dashboard assets are out of sync (a cache or proxy served mismatched files). " +
  "Hard-refresh (Ctrl+Shift+R); if it persists, purge your CDN cache for this host " +
  "and check for two running docker-updater containers.";

// isNullElementError spots render() blowing up on a missing element (a
// TypeError dereferencing null/undefined) — the mixed-asset signature — as
// opposed to a genuine fetch/data failure.
function isNullElementError(err: unknown): boolean {
  return err instanceof TypeError && /null|undefined/i.test(err.message);
}

async function refresh(): Promise<void> {
  try {
    const resp = await fetch("api/containers", { cache: "no-store" });
    if (!resp.ok) throw new Error("HTTP " + resp.status + ": " + (await resp.text()));
    latestData = (await resp.json()) as ApiResponse;
    pollFailure = null;
  } catch (err) {
    pollFailure = isNullElementError(err)
      ? OUT_OF_SYNC_HINT
      : "Failed to load container data: " + (err instanceof Error ? err.message : String(err));
  }
  repaint();
}

// jumpToPending scrolls to the first container with a held-back update, flashing
// it so "N updates pending" always points at concrete rows. Every row lives in
// a collapsible group, so reveal the group holding the target first.
function jumpToPending(): void {
  const first = document.querySelector<HTMLElement>(".row-pending");
  if (!first) return;
  const section = first.closest("details");
  if (section) section.open = true;
  first.scrollIntoView({ behavior: "smooth", block: "center" });
  first.classList.remove("row-flash");
  void first.offsetWidth; // reflow so the animation restarts on repeat clicks
  first.classList.add("row-flash");
}

// Typing in the filter and expanding a section both change what the page shows
// without any new data, so both rebuild the state — no refetch; the poll keeps
// replacing latestData underneath as usual.
function onUiChange(): void {
  repaint();
}

// REQUIRED_IDS is the startup contract between this script and index.html:
// every element id the code above dereferences unconditionally (the four group
// sections with their -rows/-summary children, the search box, the empty-state
// line, the error banner, the dry-run badge, and the summary stat cards). The
// group entries are derived from GROUPS so the list can't drift from render()'s
// own lookups.
const REQUIRED_IDS: string[] = [
  "search",
  "empty",
  "error-banner",
  "dry-run-badge",
  "stat-total",
  "stat-auto",
  "stat-manual",
  "stat-updates",
  "stat-errors",
  ...GROUPS.flatMap((g) => [g.id, g.id + "-rows", g.id + "-summary"]),
];

// renderOutOfSyncBanner replaces the cryptic "replaceChildren of null" crash
// with a readable full-width explanation of what actually happened. Inline
// styles on purpose: in the mixed-asset scenario the stylesheet may be from
// yet another build, so the banner cannot rely on any class existing.
function renderOutOfSyncBanner(missing: string[]): void {
  const banner = el(
    "div",
    {
      class: "error-banner",
      style:
        "display:block;margin:16px;padding:12px 16px;border:1px solid #f85149;" +
        "border-radius:6px;background:#3d1214;color:#ffdcd7;" +
        "font:14px/1.5 system-ui,sans-serif;",
    },
    OUT_OF_SYNC_HINT + " (missing elements: " + missing.join(", ") + ")",
  );
  document.body.prepend(banner);
}

// initDashboard wires the listeners and starts the poll loop — only ever
// called against a document that passed the REQUIRED_IDS check below.
function initDashboard(): void {
  const updatesCard = document.getElementById("card-updates");
  if (updatesCard) updatesCard.addEventListener("click", jumpToPending);

  const copyErrorsBtn = document.getElementById("copy-errors");
  if (copyErrorsBtn) copyErrorsBtn.addEventListener("click", () => void onCopyErrors());

  const copyStateBtn = document.getElementById("copy-state");
  if (copyStateBtn) copyStateBtn.addEventListener("click", () => void onCopyState());

  const searchBox = document.getElementById("search") as HTMLInputElement | null;
  if (searchBox) searchBox.addEventListener("input", onUiChange);

  // Expanding or collapsing a section changes what is on screen, so the state
  // has to follow it. render() writes the same value straight back, so this
  // cannot loop.
  for (const g of GROUPS) {
    const section = document.getElementById(g.id);
    if (section) section.addEventListener("toggle", onUiChange);
  }

  // Keyboard niceties: "/" focuses the filter box, Escape clears it.
  document.addEventListener("keydown", (e: KeyboardEvent) => {
    if (!searchBox) return;
    const target = e.target instanceof HTMLElement ? e.target : null;
    const typing = target !== null &&
      (target.tagName === "INPUT" || target.tagName === "TEXTAREA" || target.isContentEditable);
    if (e.key === "/" && !typing) {
      e.preventDefault();
      searchBox.focus();
      searchBox.select();
    } else if (e.key === "Escape" && target === searchBox) {
      searchBox.value = "";
      onUiChange();
      searchBox.blur();
    }
  });

  void refresh();
  setInterval(refresh, REFRESH_SECONDS * 1000);
}

// Startup gate: if the document is missing anything this script requires, the
// browser was served mismatched assets (an index.html from one build against a
// dashboard.js from another). Say so readably and do NOT start the poll loop —
// every render would just crash on the absent elements.
const missingIds = REQUIRED_IDS.filter((id) => document.getElementById(id) === null);
if (missingIds.length > 0) {
  renderOutOfSyncBanner(missingIds);
} else {
  initDashboard();
}
